### ISSUE TITLE
No Hiera support

### ISSUE THREAD

**Issue by ryayon** [voxpupuli/puppet-selinux#104]
Hi,

It seems there is no hiera support despite the `create_resources` declaration in the `init.pp` manifest.
1. The following Hiera entry is not seen by the module:

```
selinux_booleans:
  'httpd_can_network_relay' : {}
```
1.  However, adding the following code in the `init.pp` (which is just a `hiera_hash` declaration) makes it visible again:

```
$selinux_boolean_list = hiera('selinux_booleans', undef)
if $selinux_booleans_list {
    create_resources ( 'selinux::boolean', hiera_hash('selinux_booleans') )
}
```

The first declaration is just a simple 
And you also can add some default parameters....

I am running Puppet v 4.5.2 on CentOS7.

Are you aware about this? Do you need a PR?

Regards,
Rudy

**Comment by westbywest** [comment]
I think the correct hiera entry would be:
```
selinux::selinux_booleans:
  httpd_can_network_relay:
    value: on
```

**Comment by ryayon** [comment]
Seems weird as the code in the `boolean.pp ` is:

```
#  selinux::boolean{ 'named_write_master_zones':
#     ensure     => "on",
#     persistent => true,
#  }
#

define selinux::boolean (
  $ensure     = 'on',
  $persistent = true,
) {
......
}
```

**Comment by westbywest** [comment]
Aha, I had misread your original comment, or more specifically the code starting at [line 33](https://github.com/jfryman/puppet-selinux/blob/master/manifests/init.pp#L33) of the selinux init class.  I believe the problem is that specifying in code empty hashes as default values for parameter prevents puppet from doing automatic hiera lookup.

Try changing lines 33 to 36 in init.pp as such:
```
  $selinux_booleans,
  $selinux_modules,
  $selinux_fcontexts,
  $selinux_ports
```

Then change lines 63 to 66 to be this:
```
  if $selinux_booleans {
    create_resources('selinux::boolean', $selinux_booleans)
  }
  if $selinux_modules {
    create_resources('selinux::module', $selinux_modules)
  }
  if $selinux_fcontexts {
    create_resources('selinux::fcontext', $selinux_fcontexts)
  }
  if $selinux_ports {
    create_resources('selinux::port', $selinux_ports)
  }
```

At that point, the following hiera should work as expected:
```
selinux::selinux_booleans:
  httpd_can_network_relay:
    ensure: on
```

Note that I'm not a maintainer of this module.  You'd want to submit a PR with these changes to get their attention.

**Comment by ryayon** [comment]
Thanks.
I will prepare a PR.

**Comment by ryayon** [comment]
I just created the PR #128

**Comment by ryayon** [comment]
Issue fixed
